import Navbar from '@/components/Navbar';
import '@/styles/globals.css';

export const metadata = {
  title: 'Projeto CG',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico'
  }
};

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-br">
      <body className="h-screen flex flex-col bg-zinc-100">
        <Navbar />
        <div className="flex justify-center items-center h-full">
          {children}
        </div>
      </body>
    </html>
  );
}

export default RootLayout;
