import Navbar from '@/components/Navbar';
import './globals.css';

export const metadata = {
  title: 'Projeto CG',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className="h-screen flex flex-col bg-zinc-100">
        <Navbar />
        <div className="flex justify-center items-center h-full">
          {children}
        </div>
      </body>
    </html>
  );
}
